FT: false
FeatureExtraction: VGG
PAD: true
Prediction: CTC
SequenceModeling: BiLSTM
Transformation: None
batch_max_length: 32
batch_ratio: '1'
batch_size: 32
beta1: 0.9
contrast_adjust: 0.0
data_filtering_off: true
decode: greedy
eps: 1.0e-08
experiment_name: en_filtered
freeze_FeatureFxtraction: false
freeze_SequenceModeling: false
grad_clip: 5
hidden_size: 512
imgH: 40
imgW: 16
input_channel: 1
lang_char: abcdefghjkmnpqrstvwxyz
lr: 1.0
manualSeed: 1111
new_prediction: false
num_fiducial: 20
num_iter: 30000
number: '23456789'
optim: adam
output_channel: 512
rgb: false
rho: 0.95
saved_model: ''
select_data: train
sensitive: false
symbol: ''
total_data_usage_ratio: 1.0
train_data: all_data/anotherOCR
valInterval: 1000
valid_data: all_data/anotherOCR/eval
workers: 4
